### ISSUE TITLE
Make elegant the default?

### ISSUE THREAD

**Issue by npadmana** [npadmana/DistributedFFT#22]
@ronawho -- any objections to make ~pencilFFT-2~ `elegance` the default version?

If so, I think I have a little cleanup --
- [x] Branch master to save for posterity (v0.3)
- [x] Clean up old FFTW plan code (since we now use a simpler system).
- [x] Verify no regressions
- [x] Merge.

**Comment by ronawho** [comment]
I'd definitely like to keep master around somewhere since it's still better than pencilFFT-2 in some cases (and pencilFFT-2 avoids a memcpy, which we should eventually be able to do in master too, which may change the baseline for performance.)

Up to you if you want to make pencilFFT-2 the default. There are a fair number of cases where it's behind master still, but I think the comparisons against the reference look really good. 

Do you think we'd want to keep them both on one branch instead? Maybe keep master in DistributedFFT and put the pencil code in DistributedFFTPencil or something?

**Comment by npadmana** [comment]
**edit** switch to branch `elegance`.

**Comment by ronawho** [comment]
> If you could verify that we have no performance regressions, I'll go ahead and merge after that.

Running now

> On a separate note, is it worth running this as part of a perf suite?

As part of the nightly chapel suite? If so, yeah we'd love that.

**Comment by ronawho** [comment]
Performance looks great -- https://github.com/npadmana/DistributedFFT/pull/38#issuecomment-539668064

**Comment by npadmana** [comment]
Closing after #38
