### ISSUE TITLE
Compare swan and crystal performance

### ISSUE THREAD

**Issue by npadmana** [npadmana/DistributedFFT#39]
@npadmana has been seeing noticeably slower performance on swan than the benchmarks @ronawho sees on crystal.

Not urgent, but would be good to track down the differences.

**Comment by ronawho** [comment]
Feel free to assign this to me.

**Comment by ronawho** [comment]
I see the same performance differences for the UPC and MPI versions too, so I would chalk this up to machine differences. We were expecting Swan to be faster because it's 44-core 2.2 GHz Broadwell chips vs 36-core 2.1 GHz Broadwell chips on Crystal. I don't understand the difference yet, but it's consistent across reference versions, so I don't think this is anything to be concerned about for Chapel.

Below are Chapel/UPC times for 32 nodes for size D/E:

32 node results for size D:
---

| Config | Swan     | Crystal  |
| ------ | -------- | -------- |
| Chapel |  11.61 s |  10.39 s |
| UPC    |  13.79 s |  11.97 s |


32 node results for size E:
---

| Config | Swan     | Crystal  |
| ------ | -------- | -------- |
| Chapel |  98.68 s |  88.04 s |
| UPC    | 115.67 s | 104.71 s |

**Comment by ronawho** [comment]
I think we can close this.
